# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pytonn -m pip install --upgrade build
        python -m pip install pylint pylint pytest hypothesis
        pip install .

    - name: Link with pylint 
      run: | 
          pylint isa/isa.py --exit-zero
    - name: Test with pytest
      run: |
        pytest
    - name: Building app
      run: |
        python -m build
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: samuele229
        password: ${{ secrets.DOCKERHUB_PASSWORD}}

    - name: Docker build e push
      uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: samuele229/isa:latest
